{% set name = "hub" %}
{% set version = HUB_VERSION %}

package:
  name: "{{ name }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: f3ceafffdbc70c309fdd44654775668fa5cdca438309267a05faa6dd58636d7e

build:
  number: 0
  entry_points:
    - hub = hub.cli.command:cli
    - hub-local = hub.cli.local:cli
    - hub-dev = hub.cli.dev:cli
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - azure-storage-blob ==12.6.0
    - boto3 ==1.16.39
    - cachey ==0.2.1
    - click >=6.7,<8
    - cloudpickle ==1.6.0
    - fsspec ==0.8.5
    - gcsfs ==0.6.2
    - lz4 >=3,<4
    - msgpack-python ==1.0.2
    - numpy >=1.13.0,<2
    - outdated ==0.2.0
    - pathos >=0.2.2
    - pillow >=8.0.1
    - pip
    - psutil >=5.7.3
    - python
    - requests >=2,<3
    - s3fs ==0.4.2
    - tqdm ==4.54.1
    - zarr ==2.6.1
  run:
    - azure-storage-blob ==12.6.0
    - boto3 ==1.16.39
    - cachey ==0.2.1
    - click >=6.7,<8
    - cloudpickle ==1.6.0
    - fsspec ==0.8.5
    - gcsfs ==0.6.2
    - lz4 >=3,<4
    - msgpack-python ==1.0.2
    - numpy >=1.13.0,<2
    - outdated ==0.2.0
    - pathos >=0.2.2
    - pillow >=8.0.1
    - psutil >=5.7.3
    - python
    - requests >=2,<3
    - s3fs ==0.4.2
    - tqdm ==4.54.1
    - zarr ==2.6.1

test:
  imports:
    - hub
    - hub.api
    - hub.cli
    - hub.client
    - hub.codec
    - hub.collections
    - hub.collections.dataset
    - hub.collections.tensor
    - hub.compute
    - hub.schema
    - hub.store
    - hub.store.tests
  commands:
    - hub --help
    - hub-local --help
    - hub-dev --help
  requires:
    - mock >=1.0.1
    - pytest

about:
  home: "https://github.com/activeloopai/Hub"
  license: "Mozilla Public 2.0 (MPL 2.0)"
  license_family: MOZILLA
  license_file: 
  summary: "Activeloop Hub"
  doc_url: "https://docs.activeloop.ai/en/latest/"
  dev_url: 

extra:
  recipe-maintainers:
    - haiyangdeperci
