version: 2.1

orbs:
  slack: circleci/slack@3.4.2

workflows:
  build_and_deploy:
    jobs:
      - test:
        context: pypi
        filters:
          branches:
            only:
              - cicd-pypi
      - deploy:
          context: pypi
          requires:
            - test
          filters:
            branches:
              only:
                - cicd-pypi
#          filters:
#            tags:
#              only: /[0-9]+(\.[0-9]+)*/
#            branches:
#              ignore: /.*/

jobs:
  test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: "Running tests"
          command: |
              pytest ./
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports
#      - slack/status:
#          fail_only: true
#          webhook: $SLACK_WEBHOOK

  deploy:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: "Verify git tag vs. version"
          command: |
            python setup.py verify
      - run:
          name: "Init .pypirc"
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = $PYPI_USERNAME" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: "Create a source distribution & wheel"
          command: |
            python setup.py sdist
            python setup.py bdist_wheel
      - run:
          name: "Install twine via pip"
          command: |
            pip install twine
      - run:
          name: "Upload dist to PyPi"
          command: |
            twine upload dist/*
#      - slack/status:
#          fail_only: true
#          webhook: $SLACK_WEBHOOK

