name: Lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: Python ${{ matrix.python-version }} - ${{ matrix.os }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - 3.8
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/common.txt
          pip install -r requirements/tests.txt
          pip install -r requirements/plugins.txt
      - name: Install Hub
        run: pip install -e .
      - name: Check formatting with black
        run: |
          black --version
          black --check .
      - name: Lint docstrings with darglint
        run: |
          darglint --version
          darglint .
      - name: Check typing with mypy
        run: |
          mypy --version
          mypy .
